"""
tests/test_no_leakage.py
========================
Permanent leakage regression tests for the ETA prediction pipeline.

Run with:
    pytest tests/test_no_leakage.py -v

Or integrated into the training pipeline via train.py's leakage guard.

These tests catch the class of bug confirmed in the v5 audit:
  - A feature derived from the target (simulated_delay_min) being fed back
    to the model, inflating benchmark metrics silently.
"""
import sys
from pathlib import Path
import numpy as np
import pandas as pd
try:
    import pytest
except ImportError:
    class _MockPytest:
        @staticmethod
        def fixture(*args, **kwargs):
            def decorator(func):
                return func
            return decorator
        @staticmethod
        def mark(*args, **kwargs):
            class _Mark:
                @staticmethod
                def parametrize(*a, **kw):
                    def decorator(func):
                        return func
                    return decorator
            return _Mark()
        @staticmethod
        def skip(msg):
            print(f"[SKIPPED] {msg}")
    pytest = _MockPytest()
    pytest.mark = _MockPytest.mark()

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

TARGET_COL = "simulated_delay_min"
LEAKAGE_CORR_THRESHOLD = 0.75
# Single-feature MAE must be at least 1.5x worse than the full model to pass.
SINGLE_FEAT_RATIO_MIN = 1.5


@pytest.fixture(scope="module")
def engineered_train_df():
    """
    Load the processed training split (generated by train.py's feature pipeline).
    If not available, skip all tests with a clear message.
    """
    from src.config import PROCESSED_TRAIN_PATH
    if not PROCESSED_TRAIN_PATH.exists():
        pytest.skip(
            f"Processed training data not found at '{PROCESSED_TRAIN_PATH}'. "
            f"Run 'python -u src/train.py' first to generate it."
        )
    df = pd.read_csv(PROCESSED_TRAIN_PATH)
    if TARGET_COL not in df.columns:
        pytest.skip(f"Target column '{TARGET_COL}' missing from processed train data.")
    return df


def _get_full_model_mae(df: pd.DataFrame) -> float:
    """
    Rough proxy for full-model MAE — computed from a multi-feature linear baseline
    on the same training data. Used only as the denominator in the single-feature
    ratio check; the actual model is far stronger, so this is a conservative bound.
    """
    from src.features import FINAL_FEATURE_COLS
    available = [c for c in FINAL_FEATURE_COLS if c in df.columns]
    X = df[available].fillna(0)
    y = df[TARGET_COL]
    pred = LinearRegression().fit(X, y).predict(X)
    return float(mean_absolute_error(y, pred))


# ---------------------------------------------------------------------------
# Test 1: No feature has near-perfect correlation with the target
# ---------------------------------------------------------------------------
class TestCorrelationLeakageGuard:
    # Strict check — event features that must not be derived from the target (v5 leak fix)
    FEATURES_TO_CHECK = [
        "event_elapsed_min",
        "event_expected_min",
    ]

    @pytest.mark.parametrize("col", FEATURES_TO_CHECK)
    def test_feature_not_near_perfectly_correlated_with_target(self, col, engineered_train_df):
        """
        Any engineered feature with |corr| >= 0.75 against the target is likely
        leaking outcome information. Fails loudly so it is caught before benchmarking.
        """
        if col not in engineered_train_df.columns:
            pytest.skip(f"Column '{col}' not present in training data (may not be generated).")

        corr = engineered_train_df[[col, TARGET_COL]].corr().iloc[0, 1]
        assert abs(corr) < LEAKAGE_CORR_THRESHOLD, (
            f"[LEAKAGE SUSPECTED] '{col}' has |corr|={abs(corr):.4f} >= {LEAKAGE_CORR_THRESHOLD} "
            f"with target '{TARGET_COL}'. This is a strong leakage signal. "
            f"Check whether '{col}' is derived from the target."
        )


# ---------------------------------------------------------------------------
# Test 2: No single event feature can nearly match the full-model MAE alone
# ---------------------------------------------------------------------------
class TestSingleFeatureSanityCheck:
    EVENT_FEATURES = ["event_elapsed_min", "event_expected_min"]

    @pytest.mark.parametrize("col", EVENT_FEATURES)
    def test_single_feature_mae_not_suspiciously_close_to_full_model(self, col, engineered_train_df):
        """
        A single feature model that approaches full-model MAE is a classic leakage
        signature (Step 2 of the v5 audit). event_elapsed_min or event_expected_min
        alone should be significantly weaker than the full multi-feature model.
        """
        if col not in engineered_train_df.columns:
            pytest.skip(f"Column '{col}' not present in training data.")

        y = engineered_train_df[TARGET_COL]
        X_single = engineered_train_df[[col]].fillna(0)
        single_mae = float(mean_absolute_error(y, LinearRegression().fit(X_single, y).predict(X_single)))

        full_mae = _get_full_model_mae(engineered_train_df)

        ratio = single_mae / (full_mae + 1e-9)
        assert ratio >= SINGLE_FEAT_RATIO_MIN, (
            f"[LEAKAGE SUSPECTED] '{col}' alone achieves MAE={single_mae:.2f} min "
            f"vs full-feature linear baseline MAE={full_mae:.2f} min "
            f"(ratio={ratio:.2f} < required {SINGLE_FEAT_RATIO_MIN}). "
            f"A single feature this powerful is a strong leakage signal."
        )


# ---------------------------------------------------------------------------
# Test 3: event_duration (the old leaking field) must not exist in feature cols
# ---------------------------------------------------------------------------
class TestBannedColumnAbsence:
    def test_event_duration_not_in_feature_cols(self):
        """
        The old target-derived field 'event_duration' must not appear in
        FINAL_FEATURE_COLS or STATIC_FEATURE_COLS after the v6 fix.
        """
        from src.features import FINAL_FEATURE_COLS, STATIC_FEATURE_COLS
        assert "event_duration" not in FINAL_FEATURE_COLS, (
            "'event_duration' found in FINAL_FEATURE_COLS — this is the leaking field "
            "removed in v6. Remove it and use 'event_elapsed_min' / 'event_expected_min'."
        )
        assert "event_duration" not in STATIC_FEATURE_COLS, (
            "'event_duration' found in STATIC_FEATURE_COLS — same leakage concern."
        )

    def test_new_event_features_present_in_feature_cols(self):
        """
        The two replacement features must be registered in FINAL_FEATURE_COLS.
        """
        from src.features import FINAL_FEATURE_COLS
        assert "event_elapsed_min" in FINAL_FEATURE_COLS, (
            "'event_elapsed_min' not found in FINAL_FEATURE_COLS. "
            "Register it as a leakage-free replacement for 'event_duration'."
        )
        assert "event_expected_min" in FINAL_FEATURE_COLS, (
            "'event_expected_min' not found in FINAL_FEATURE_COLS. "
            "Register it as a leakage-free replacement for 'event_duration'."
        )


if __name__ == "__main__":
    print("Running Permanent Leakage Regression Tests...")
    t3 = TestBannedColumnAbsence()
    t3.test_event_duration_not_in_feature_cols()
    print("  [PASS] 'event_duration' absent from feature columns")
    t3.test_new_event_features_present_in_feature_cols()
    print("  [PASS] 'event_elapsed_min' and 'event_expected_min' registered in feature columns")

    from src.config import PROCESSED_TRAIN_PATH
    if PROCESSED_TRAIN_PATH.exists():
        df = pd.read_csv(PROCESSED_TRAIN_PATH)
        t1 = TestCorrelationLeakageGuard()
        for col in t1.FEATURES_TO_CHECK:
            if col in df.columns:
                t1.test_feature_not_near_perfectly_correlated_with_target(col, df)
                print(f"  [PASS] Feature correlation guard: '{col}'")
        t2 = TestSingleFeatureSanityCheck()
        for col in t2.EVENT_FEATURES:
            if col in df.columns:
                t2.test_single_feature_mae_not_suspiciously_close_to_full_model(col, df)
                print(f"  [PASS] Single feature MAE ratio guard: '{col}'")
    else:
        print(f"  [INFO] Processed train path {PROCESSED_TRAIN_PATH} does not exist; skipping dataset correlation checks.")

    print("\nALL LEAKAGE REGRESSION TESTS PASSED!")
